import { build, context } from 'esbuild';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const watch = process.argv.includes('--watch');
const development = watch || process.argv.includes('--dev');
const options = {
  absWorkingDir: root,
  entryPoints: ['src/main.mjs'],
  outfile: development ? 'dist/jumbo-checklist.dev.user.js' : 'dist/jumbo-checklist.user.js',
  bundle: true,
  write: false,
  format: 'iife',
  platform: 'browser',
  target: ['safari15.4'],
  loader: { '.css': 'text' },
  minify: !development,
  // Keep generated multiline strings escaped (including significant PDF spaces).
  supported: development ? {} : { 'template-literal': false },
  sourcemap: development ? 'inline' : false,
  charset: 'utf8',
  legalComments: 'none',
  plugins: [{
    name: 'userscript-header',
    setup(builder) {
      // Reload metadata on each build, including watch rebuilds.
      builder.onEnd(async result => {
        if (result.errors.length) return;
        const metadata = (await readFile(new URL('../src/metadata.txt', import.meta.url), 'utf8')).trimEnd();
        const header = metadata + '\n// Generated from src/. Do not edit this file directly.\n';
        for (const output of result.outputFiles) {
          await mkdir(dirname(output.path), { recursive: true });
          const temporary = output.path + '.tmp';
          // Prepending metadata shifts generated lines: keep debugger mappings accurate.
          const body = output.text.replace(/(sourceMappingURL=data:application\/json;base64,)(\S+)/, (_, prefix, encoded) => {
            const map = JSON.parse(Buffer.from(encoded, 'base64').toString('utf8'));
            map.mappings = ';'.repeat(header.split('\n').length - 1) + map.mappings;
            return prefix + Buffer.from(JSON.stringify(map)).toString('base64');
          });
          await writeFile(temporary, header + body);
          await rename(temporary, output.path);
        }
      });
      builder.onLoad({ filter: /src[\\/]main\.mjs$/ }, async args => ({
        contents: await readFile(args.path, 'utf8'),
        loader: 'js',
        watchFiles: [fileURLToPath(new URL('../src/metadata.txt', import.meta.url))],
      }));
    },
  }],
  logLevel: 'info',
};

if (watch) {
  const session = await context(options);
  await session.watch();
  console.log('Watching src/. Refresh the fixture or reload the userscript after changes.');
} else {
  await build(options);
}
